# Generated by Django 5.2.6 on 2025-09-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('travel', '여행'), ('football', '축구'), ('cat', '고양이')], default='free', max_length=30, verbose_name='카테고리'),
        ),
    ]
